version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3.11-management
    build:
      dockerfile: ./RabbitMQ.dockerfile
    hostname: ceis.rabbitmq
    container_name: ceisrabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
      - "15671:15671"
      - "15674:15674"
      - "15675:15675"
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=123123
    restart: always